- name: Install ntpd service
  package:
    name:
      - ntp
      - ntpdate

- name: Ensure ntpd is started
  service:
    name: ntpd
    state: started
    enabled: yes
  register: ntpd_start

- name: Waiting for correct time
  when: ntpd_start is changed
  debug:
    msg: "
      Date on {{ ansible_fqdn }} is {{ ansible_date_time.date }}-{{ ansible_date_time.hour }},
      local date is {{ lookup('pipe', 'date +%Y-%m-%d-%H')}}
    "

- name: Acquire correct time
  when: ntpd_start is changed
  debug:
    msg: "
      Date on {{ ansible_fqdn }} is {{ ansible_date_time.date }}-{{ ansible_date_time.hour }},
      local date is {{ lookup('pipe', 'date +%Y-%m-%d-%H')}}
    "
  until: ansible_date_time.date + '-' + ansible_date_time.hour == lookup('pipe', 'date +%Y-%m-%d-%H')
  delay: 5
  retries: 24