- name: Install ntpd service
  package:
    name:
      - ntp
      - ntpdate

- name: Ensure ntpd is started
  service:
    name: ntpd
    state: started
    enabled: yes
  register: ntpd_start

- name: Waiting for correct time
  when: ntpd_start is changed
  debug:
    msg: Waiting for ntp to set the correct time. Using {{ lookup('pipe', "date '+%Y-%m-%d H%H'") }} as current time.

- name: Acquire correct time
  when: ntpd_start is changed
  shell: "date '+%Y-%m-%d H%H'"
  register: remote_date
  until: remote_date.stdout == lookup('pipe', "date '+%Y-%m-%d H%H'")
  delay: 5
  retries: 24