- name: Install ntpd service
  package:
    name:
      - ntp
      - ntpdate

- name: Ensure ntpd is started
  service:
    name: ntpd
    state: started
    enabled: yes
  register: ntpd_start

# - name: Pause for 5 seconds to acquire correct time
#   when: ntpd_start is changed
#   pause:
#     seconds: 5