- pause:
    prompt: "Enter the admin password you would like to use for all services (at least 6 characters)"
    echo: no
  register: admin_pass_input
  until: (admin_pass_input.user_input|length) >= 6
  retries: 25
  delay: 0
  no_log: true

- pause:
    prompt: "Confirm the admin password"
    echo: no
  register: pass_check
  until: pass_check.user_input == admin_pass_input.user_input
  retries: 3
  delay: 0
  no_log: true

- name: Set the password
  set_fact:
    admin_pass: "{{ admin_pass_input.user_input }}"
  no_log: true