
# All ESGF Node Componenets

- hosts: all
  tasks:
    # Get the admin password
    - name: Include the passwd role
      block:
        - include_role:
            name: passwd
      tags: always

    - name: Include the main role
      include_role:
        name: main

    - name: Start services
      block:
        - include_role:
            name: start
      tags:
        - start
        - never

    - name: Stop services
      block:
        - include_role:
            name: stop
      tags:
        - stop
        - never