
# All ESGF Node Componenets

- hosts: all
  become: yes
  tasks:
    # Get the admin password
    - name: Include the passwd role
      block:
        - include_role:
            name: passwd
      tags: always
      when: admin_pass is not defined

    - name: Include the main role
      block:
        - include_role:
            name: main
      tags:
        - install

    - name: Start services
      block:
        - include_role:
            name: start
      tags:
        - start
        - never

    - name: Stop services
      block:
        - include_role:
            name: stop
      tags:
        - stop
        - never