
# All ESGF Node Componenets

- hosts: all
  tasks:
    # Get the admin password
    - name: Include the passwd role
      include_role:
        name: passwd

    - name: Include the data role
      block:
        - include_role:
            name: data
      become: yes
      when: "'data' in group_names"
      tags: data
    - name: Include the idp role
      block:
        - include_role:
            name: idp
      become: yes
      when: "'idp' in group_names"
      tags: idp
    - name: Include the index role
      block:
        - include_role:
            name: index
      become: yes
      when: "'index' in group_names"
      tags: index