- hosts: all
  strategy: free
  become: yes
  tasks:
    - name: Start
      block:
        - include_role:
            name: start
      tags: start
    - name: Stop
      block:
        - include_role:
            name: stop
      tags: stop