- hosts: all
  # strategy: free
  become: yes
  connection: paramiko
  any_errors_fatal: true
  tasks:
    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always

    - name: Node Status
      block:
        - include_role:
            name: node_status
      tags: index
      when: "'index' in group_names"
