
# All ESGF Node Componenets

- hosts: all
  # strategy: free
  become: yes
  connection: paramiko
  any_errors_fatal: true
  tasks:
    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always
  
    - name: Verify variables
      block:
        - include_role:
            name: verify
      tags: always

    - name: Base
      block:
        - include_role:
            name: base
      tags:
        - always
        - base

    - name: IDP
      block:
        - include_role:
            name: idp
      tags: idp
      when: "'idp' in group_names"

    - name: Index
      block:
        - include_role:
            name: index
      tags: index
      when: "'index' in group_names"

    - name: Data
      block:
        - include_role:
            name: data
      tags: data
      when: "'data' in group_names"

    - name: Publisher
      block:
        - include_role:
            name: publisher
      tags:
        - data
        - publisher
      when: "'data' in group_names"
