- hosts: all
  become: yes
  tasks:
    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always
      when: admin_pass is not defined

    - name: Install Globus GridFTP key/cert
      include_role:
        name: globus_certs

    - name: Install Globus MyProxy key/cert/signing-policy
      include_role:
        name: myproxy_certs
    
    - name: Run the globus-connect-server-id-setup Command
      command: globus-connect-server-id-setup -c {{ myproxy.scripts.dir }}/globus-connect-server.conf --force
    - name: Run globus-connect-server-io-setup
      command: globus-connect-server-io-setup -c /etc/globus-connect-server-esgf.conf --force