- hosts: all
  connection: paramiko
  become: yes
  tasks:
    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always

    - name: Verify variables
      block:
        - include_role:
            name: verify
      tags: always

    # Install Certs
    - name: Install Globus Identity key/cert
      include_role:
        name: globus_certs

    # Install GCS config for GridFTP and register
    - name: Register Globus Connect Server
      when:
        - globus_user is defined
        - globus_pass is defined
      command: 'globus-connect-server-setup --force'