- hosts: all
  connection: paramiko
  become: yes
  tasks:
    # Get the admin password
    - name: Include the admin passwd role
      block:
        - include_role:
            name: passwd
      tags: always
    
    - name: Verify variables
      block:
        - include_role:
            name: verify
      tags: always

    - include_role:
        name: httpd
    - include_role:
        name: tomcat
        tasks_from: certs.yml