
# Create Globus user and group
- name: globus Group
  group:
    name: globus

- name: globus User
  user:
    name: globus
    groups: globus
    password: "{{ admin_pass|hash('sha512') }}" # Needs to be hashed sha512

- name: Create needed gridftp directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/gridftp.d
    - /usr/local/esg-usage-parser
    - /usr/local/esg-usage-parser/src
    - /usr/local/esg-usage-parser/log
    - "{{ esg.log }}"
    - "{{ gridftp.chroot }}"

- name: Install globus-connect-esgf_gridftp config
  template:
    src: gridftp/globus-connect-esgf_gridftp.j2
    dest: /etc/gridftp.d/globus-connect-esgf

# Setup esg_usage_parser
- name: Install the esg_usage_parser for GridFTP Metrics
  unarchive:
    remote_src: yes
    src: "{{ assets.base }}/esg_usage_parser-0.1.1.tar.bz2"
    dest: /usr/local/esg-usage-parser/src

- name: Install the esg_usage_parser config
  template:
    src: gridftp/esg_usage_parser.conf.j2
    dest: /usr/local/esg-usage-parser/esg_usage_parser.conf

- name: Setup cron job for esg_usage_parser
  cron:
    name: Run esg_usage_parser
    minute: 5
    hour: "0,12"
    job: "ESG_USAGE_PARSER_CONF=/usr/local/esg-usage-parser/esg_usage_parser.conf /usr/local/esg-usage-parser/src/esg_usage_parser"

# ESG SAML Auth
- name: Install esgsaml_auth.conf
  template:
    src: gridftp/esgsaml_auth.conf.j2
    dest: /etc/grid-security/esgsaml_auth.conf

- name: Install globus-esgf config file
  copy:
    src: gridftp/globus-esgf
    dest: /etc/gridftp.d/globus-esgf

- name: Add a mapfile entry
  command: grid-mapfile-add-entry -dn '^.*$' -ln globus

- name: Create chroot jail for GridFTP
  command: globus-gridftp-server-setup-chroot -r {{ gridftp.chroot }}

- name: Install the resolv.conf into the GriFTP chroot
  copy:
    remote_src: yes
    src: /etc/resolv.conf
    dest: "{{ gridftp.chroot }}/etc/resolv.conf"