# Open the GridFTP control port on CentOS 7
- name: Configure firewalld for GridFTP control
  when: is_7 and (configure_centos7_firewalld is defined and configure_centos7_firewalld)
  firewalld:
    port: 2811/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Configure iptables for GridFTP control
  when: is_6 and (configure_centos6_iptables is defined and configure_centos6_iptables)
  iptables:
    chain: INPUT
    destination_port: 2811
    jump: ACCEPT
    protocol: tcp
    match: tcp
    action: insert
    rule_num: 5
  register: iptables_conf_gftp_ctrl

# Open the GridFTP data ports on CentOS 7
- name: Configure firewalld for GridFTP data ports
  when: is_7 and (configure_centos7_firewalld is defined and configure_centos7_firewalld)
  firewalld:
    port: 50000-51000/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Configure iptables for GridFTP data
  when: is_6 and (configure_centos6_iptables is defined and configure_centos6_iptables)
  iptables:
    chain: INPUT
    destination_port: 50000:51000
    jump: ACCEPT
    protocol: tcp
    match: multiport
    action: insert
    rule_num: 5
  register: iptables_conf_gftp_data

- name: Save iptables change
  when: is_6 and (configure_centos6_iptables is defined and configure_centos6_iptables) and (iptables_conf_gftp_data is changed or iptables_conf_gftp_ctrl is changed)
  command: "service iptables save"
  args:
    warn: no