

- name: myproxy Group
  when: is_6
  group:
    name: myproxy

- name: myproxy User
  when: is_6
  user:
    name: myproxy
    groups: myproxy

- name: Ensure the myproxy user can read the appropriate password file
  when: is_7
  user:
    name: myproxy
    groups: tomcat
    append: yes

# Install myproxy scripts for validating credentials and the conda env in which they will run
- name: Create myproxy conda env
  command: "{{ conda.exe }} create -y -n {{ myproxy.env }} 'python<3' 'pyopenssl' 'psycopg2<2.8'"
  args:
    creates: "{{ conda.envs }}/{{ myproxy.env }}"

- name: Create scripts dir
  file:
    path: "{{ myproxy.scripts.dir }}"
    state: directory

- name: Install extapp
  template:
    src: myproxy/scripts/esg_attribute_callout_app.j2
    dest: "{{ myproxy.scripts.extapp }}"
    mode: 0751

- name: Install mapapp
  template:
    src: myproxy/scripts/myproxy-certificate-mapapp.j2
    dest: "{{ myproxy.scripts.mapapp }}"
    mode: 0751

- name: Install retriever
  template:
    src: myproxy/scripts/retriever.py.j2
    dest: "{{ myproxy.scripts.retriever }}"

# Install config files into /etc/myproxy.d
- name: Create /etc/myproxy.d
  file:
    path: /etc/myproxy.d
    state: directory

- name: Install the Globus Connect ESGF config to /etc/myproxy.d
  template:
    src: myproxy/globus-connect-esgf.j2
    dest: /etc/myproxy.d/globus-connect-esgf

- name: Install /etc/myproxy.d/myproxy-esgf
  template:
    src: myproxy/myproxy-esgf.j2
    dest: /etc/myproxy.d/myproxy-esgf

# Install PAM config files fo postgres auth
- name: Install pam_pgsql.conf
  template:
    src: myproxy/etc_pam_pgsql.conf.j2
    dest: /etc/pam_pgsql.conf
    mode: 0600
    owner: myproxy
    group: myproxy

- name: Install pam.d/myproxy
  copy:
    src: myproxy/etc_pam.d_myproxy
    dest: /etc/pam.d/myproxy

# Install the config file used by the myproxy server
- name: Install myproxy-server.config
  template:
    src: myproxy/myproxy-server.config.j2
    dest: /etc/myproxy-server.config
    mode: 0600
    owner: myproxy
    group: myproxy

- name: Install myproxy-server.config
  template:
    src: myproxy/myproxy-server.config.j2
    dest: "{{ myproxy.scripts.dir }}/myproxy-server.config"
    mode: 0600
    owner: myproxy
    group: myproxy

# Ensure the myproxy user:group has the correct ownership for CentOS7
- name: Set myproxy permissions
  file:
    path: "{{ item }}"
    owner: myproxy
    group: myproxy
    recurse: yes
  loop:
    - /etc/myproxy.d
    - /var/lib/globus-connect-server
    - "{{ myproxy.scripts.dir }}"
    - "{{ grid_security.dir }}/myproxy"

# Set ownership as root user on Cent OS 6
- name: Set CentOS 6 MyProxy permissions
  when: is_6
  file:
    path: "{{ myproxy.ca.dir }}/store"
    owner: root
    recurse: yes