
dependencies:
  - { role: tomcat_webapp, webapp: "{{ idp_webapp }}", when: skip_deps is not defined or not skip_deps }
  - { role: schema_migrate, egg: "{{ security.egg }}", when: skip_deps is not defined or not skip_deps }