
dependencies:
  - { role: globus_tools }
  - { role: globus_certs }
  - { role: myproxy_tools }
  - { role: myproxy_certs }
  - { role: tomcat_webapp, webapp: "{{ idp_webapp }}" }
  - { role: schema_migrate, egg: "{{ security.egg }}" }