
- name: Download the {{ exporter.name }} for monitoring
  unarchive:
    remote_src: yes
    validate_certs: no
    src: "{{ exporter.src }}"
    dest: /tmp
    creates: /tmp/{{ exporter.full_name }}

- name: Install the {{ exporter.name }} for monitoring
  command: "cp -R /tmp/{{ exporter.full_name }} {{ exporter.dir }}"
  args:
    creates: "{{ exporter.dir }}"

- name: Install the {{ exporter.name }} initd script
  template:
    src: exporters/initd.exporter.j2
    dest: /etc/init.d/{{ exporter.name }}
    mode: 0750

- name : Install the {{ exporter.name }} proxy config
  template:
    src: exporters/httpd{{ httpd_version }}/exporter.httpd.conf.j2
    dest: "{{ httpd.ssl_proxy_dir }}/{{ exporter.name }}.conf"

- name: Set prometheus ownership
  file:
    path: "{{ exporter.dir }}"
    owner: prometheus
    group: prometheus
    recurse: yes