
- name: prometheus Group
  group:
    name: prometheus

- name: prometheus User
  user:
    name: prometheus
    groups: prometheus

- name: Install all exporters
  include_tasks: install.yml
  loop: "{{ prometheus.exporters }}"
  loop_control:
    loop_var: exporter

- name: Install queries.yml for the Postgres exporter
  copy:
    src: queries.yml
    dest: /usr/local/postgres_exporter/queries.yml
