
- name: Download schema migration script {{ egg.script }}
  get_url:
    url: "{{ egg.url }}"
    dest: "/tmp/{{ egg.name }}"
  register: schema_download

- name: Create {{ schema_migrate.env }} conda env
  command: "{{ conda.exe }} create -y -n {{ schema_migrate.env }} 'python<3' pip"
  args:
    creates: "{{ conda.envs }}/{{ schema_migrate.env }}"

- name: Install and execute schema migration
  import_tasks: install.yml