
- name: Download schema migration script {{ egg.script }}
  get_url:
    url: "{{ egg.url }}"
    dest: "/tmp/{{ egg.name }}"
  register: schema_download

- name: Create {{ schema_migrate.env }} conda env
  command: "{{ conda.exe }} env create -f /esg/conda_env_files/schema-migrate_env.yml"
  args:
    creates: "{{ conda.envs }}/{{ schema_migrate.env }}"

- name: Install and execute schema migration
  when: schema_download is changed
  import_tasks: install.yml
