
- name: Install Globus IDP services
  yum:
    disable_gpg_check: yes
    name: 
      - globus-connect-server-id
      - mhash
      - pam-pgsql

- name: Import myproxy tasks
  import_tasks: myproxy.yml
