
- name: Create IDP Webapp Directory
  file:
    path: "{{ tomcat.webapps }}/{{ idp_webapp.name }}"
    state: directory

- name: IDP Webapp Download
  unarchive:
    src: "{{ idp_webapp.url }}"
    dest: "{{ tomcat.webapps }}/{{ idp_webapp.name }}"
    remote_src: yes
    creates: "{{ tomcat.webapps }}/{{ idp_webapp.name }}"