
- name: Ensure required dbs exist
  become: yes  
  become_user: postgres
  postgresql_db:
    name: "{{ item }}"
  with_items: "{{ idp_db.dbs }}"

- name: Import slcs tasks
  import_tasks: slcs.yml

- name: Import security tasks
  import_tasks: security.yml

- name: Import globus tasks
  import_tasks: globus.yml