
- name : Install the Globus Connect Server Config
  template:
    src: myproxy/globus-connect-server.conf.j2
    dest: "{{ myproxy.scripts.dir }}/globus-connect-server.conf"

- name: Run the globus-connect-server-id-setup Command
  command: globus-connect-server-id-setup -c {{ myproxy.scripts.dir }}/globus-connect-server.conf