- name: Java Download
  unarchive:
    src: "{{ java.src }}"
    dest: /usr/local
    remote_src: yes
    creates: "/usr/local/{{ java.root_dir }}"
  register: java_download

- name: Check for java symlink
  stat:
    path: "{{ java.path }}"
  register: java_link

- name: Remove {{ java.path }} if it exists and is not a symlink
  when: java_link.stat.exists and not java_link.stat.islnk
  file:
    path: "{{ java.path }}"
    state: absent

- name: Install java
  file:
    dest: "{{ java.path }}"
    src: "/usr/local/{{ java.root_dir }}"
    state: link