
# Ensure httpd Webserver is installed
- name: Ensure the apache webserver installed
  package:
    name:
      - "{{ pkgs.apache }}"
      - "mod_ssl"

# Ensure Tomcat Webserver is installed
- name: Import Tomcat Install
  import_tasks: tomcat.yml

# Add the specified webapp as a remote .war file
- name: "Create {{ webapp.name }} Webapp Directory"
  file:
    path: "{{ tomcat.webapps }}/{{ webapp.name }}"
    state: directory

- name: "{{ webapp.name }} Webapp Download"
  unarchive:
    src: "{{ webapp.url }}"
    dest: "{{ tomcat.webapps }}/{{ webapp.name }}"
    remote_src: yes
    creates: "{{ tomcat.webapps }}/{{ webapp.name }}/WEB-INF"

- name: "Set {{ webapp.name }} Webapp Ownership"
  file:
    path: "{{ tomcat.webapps }}/{{ webapp.name }}"
    owner: tomcat
    group: tomcat
    recurse: yes

# Add configuration files