# All of these steps are done locally as the pyopenssl version is not
#   sufficient ( needs >=.15 ) on CentOS 6
- name: Create local directory for generating certs and keys
  local_action:
    module: file
    path: /tmp/tempcerts
    state: directory

# Setup self-signed CA
- name: Create Self-Signed CA Private Key
  local_action:
    module: openssl_privatekey
    path: /tmp/tempcerts/ca.pem

- name: Create Self-Signed CA CSR
  local_action:
    module: openssl_csr
    path: /tmp/tempcerts/ca.csr
    privatekey_path: /tmp/tempcerts/ca.pem
    common_name: CA-{{ ansible_nodename }}

- name: Generate a Self Signed OpenSSL certificate
  local_action:
    module: openssl_certificate
    path: /tmp/tempcerts/ca.crt
    privatekey_path: /tmp/tempcerts/ca.pem
    csr_path: /tmp/tempcerts/ca.csr
    provider: selfsigned

# Setup hostkey signed by self-signed CA
- name: Create Self-Signed CA Private Key
  local_action:
    module: openssl_privatekey
    path: /tmp/tempcerts/host.pem

- name: Create Self-Signed CA CSR
  local_action:
    module: openssl_csr
    path: /tmp/tempcerts/host.csr
    privatekey_path: /tmp/tempcerts/host.pem
    common_name: "{{ ansible_nodename }}"

- name: Generate a Self Signed OpenSSL certificate
  local_action:
    module: openssl_certificate
    path: /tmp/tempcerts/host.crt
    csr_path: /tmp/tempcerts/host.csr
    ownca_path: /tmp/tempcerts/ca.crt
    ownca_privatekey_path: /tmp/tempcerts/ca.pem
    provider: ownca


# Copy files into place
- name: Copy cert and key files to {{ ansible_nodename }}
  copy:
    src: /tmp/tempcerts
    dest: /etc/ #"{{ tempca.dir }}"

- name: Copy key into place
  copy:
    remote_src: yes
    src: "{{ tempca.host.key }}"
    dest: "{{ httpd.hostkey }}"

- name: Copy cert into place
  copy:
    remote_src: yes
    src: "{{ tempca.host.cert }}"
    dest: "{{ httpd.hostcert }}"

- name: Copy temp CA cert into place
  copy:
    remote_src: yes
    src: "{{ tempca.ca.cert }}"
    dest: "{{ httpd.cachain }}"