
- name: Create esg tomcat config directory
  file:
    path: "{{ esg.config.dir }}/tomcat"
    state: directory

# Load certificates Tomcat will trust
- name: Get trusted certificates
  get_url:
    url: "{{ tomcat.ts.url }}"
    dest: "{{ tomcat.ts.path }}"

- name: Import web CA into Truststore
  java_cert:
    cert_path: "{{ httpd.cachain }}"
    keystore_path: "{{ tomcat.ts.path }}"
    keystore_pass: "{{ tomcat.ts.pass }}"
    cert_alias: my_esgf_node
    executable: "{{ java.path }}/bin/keytool"

# Load the hostkey and hostcert into the tomcat keystore
- name: Load host key
  no_log: true
  slurp:
    src: "{{ httpd.hostkey }}"
  register: keycontents

- name: Load host cert
  no_log: true
  slurp:
    src: "{{ httpd.hostcert }}"
  register: certcontents

- name: Create Keystore
  no_log: true
  java_keystore:
    private_key: "{{ keycontents['content'] | b64decode }}"
    certificate: "{{ certcontents['content'] | b64decode }}"
    name: my_esgf_node 
    dest: "{{ tomcat.ks.path }}"
    password: "{{ tomcat.ks.pass }}"
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ java.path }}/bin"

# Install Tomcat configuration files
- name: Install server.xml
  template:
    src: server.xml.j2
    dest: "{{ tomcat.path }}/conf/server.xml"

- name: Install setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat.path }}/bin/setenv.sh"

- name: Install tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{ esg.config.dir }}/tomcat/tomcat-users.xml"
    force: no

- name: Install context.xml
  copy:
    src: context.xml
    dest: "{{ tomcat.path }}/conf/context.xml"