
- name: Create esg tomcat config directory
  file:
    path: "{{ esg.config.dir }}/tomcat"
    state: directory

- name: Include certificate tasks
  include_tasks: certs.yml

# Install Tomcat configuration files
- name: Install server.xml
  template:
    src: server.xml.j2
    dest: "{{ tomcat.path }}/conf/server.xml"

- name: Install setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat.path }}/bin/setenv.sh"

- name: Install tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{ esg.config.dir }}/tomcat/tomcat-users.xml"
    force: no

- name: Install context.xml
  copy:
    src: context.xml
    dest: "{{ tomcat.path }}/conf/context.xml"