

# Trusted, signed, gridftp cert and key
- name: Copy globus hostkey into place
  when: globushostkey is defined
  copy:
    remote_src: yes
    src: "{{ globushostkey }}"
    dest: "{{ grid_security.host.key }}"
    mode: 0600

- name: Copy globus hostcert into place
  when: globushostcert is defined
  copy:
    remote_src: yes
    src: "{{ globushostcert }}"
    dest: "{{ grid_security.host.cert }}"

- name: Download trusted certificates for Globus
  unarchive:
    remote_src: yes
    src: "{{ assets.base }}/esg_trusted_certificates.tar"
    dest: /tmp

- name: Install trusted certificates for Globus
  shell: >
    cp /tmp/esg_trusted_certificates/* {{ grid_security.cert_dir }}

- name: Check if GridFTP is present
  stat:
    path: "{{ gridftp.chroot }}"
  register: gridftp_chroot

- name: Copy certificates over if it is
  when: gridftp_chroot.stat.exists
  shell: >
    cp {{ grid_security.cert_dir }}/* {{ gridftp.chroot }}{{ grid_security.cert_dir }}/