
### Admin password, specification required, see options
##
### An admin password, at least 6 characters, is required and will be used
### for the services being installed on a node.
##
## The password priority goes like this:
## 1. The contents of /esg/config/.esgf_pass on the Node, the managed machine.
##    Feel free to write this remote file manually if you would not like
##    to store the password in this host variable file.
##
## 2. The 'admin_pass' variable below. Note Ansible supports encrypting 
##    variable files, using Vault:
##    https://docs.ansible.com/ansible/latest/user_guide/vault.html
##
## *The password must be specified in at least one of the above two places*
#admin_pass:

### Keys and Certificates
# General options:
# 1. Whatever is at the path that is specified in the host's
#    variable file will be installed, whether or not the destination 
#    path is already present on the managed machine.
#    Paths specified are on the *managed* machine.
#    Note that the path specifed here may also be the destination path, 
#    but is is still required to be specified.
# OR
# 2. Ansible will generate the key certificate pair and install it
#    if the corresponding generate_* variable is uncommented and set
#    to true. See the below certificate sections.

### Filebeat
##
### The paths to the certifcate and key files that will
### authenticate the filebeat log transmitter to the logstash
### collector. These may be the same as the globus key and cert below.
#
#filebeatcert:
#filebeatkey:

### Keys and Certificates for Globus Services
##
### The paths on the *managed* machine to the respective
### key/cert that have been signed by ESGF. If these
### have not been obtained for a node, specify generate_*: true.
##
### One of these two options must be sepcified for both globus
### and myproxy (if applicable to this host).
#
#globushostcert:
#globushostkey:
# OR
#generate_globus: true|false
#
#myproxycacert:
#myproxycakey:
#myproxy_signing_policy:
# OR
#generate_myproxyca: true|false

### Keys and Certificates for Web Services, httpd and tomcat
##
### The paths on the *managed* machine to the respective 
### key/cert that have been signed by a commonly trusted 
### certificate authority. These are required to operate
### a production ESGF Node. As an alternative to costly 
### key/certificate pairs see the LetsEncrypt Section below.
##
### For test cases it is okay to simply specify generate_httpd: true
### Note this will not be valid for production and will not 
### create browser trusted certificates.
##
### One of these three options must be sepcified.
##
#hostkey_src:
#hostcert_src:
#cachain_src:
# OR
#See the LetsEncrypt Section below
# OR
#generate_httpd: true|false

### LetsEncrypt Certificates for Web Services
##
### LetsEncrypt certificates are browser trusted certificates
### that can be obtained in an automated fashion by proving
### you control the domain. They are valid for a limited time, 
### a few months, but can be easily renewed.
### In order for this to work your host must be publicly
### available at deployment time.
### This variable has no effect if the above host key/cert/chain
### variables for web services are specified.
##
### Leave unspecified to not attempt to retrieve LetsEncrypt certs.
##
#try_letsencrypt: true|false


### Globus Services
##
### This information is used to connect the node
### to the Globus system. Note globus_user should
### *not* include the "@globusid.org" portion.
##
### Leave unspecified and the Globus Connect Server 
### setup steps will be skipped.
##
#globus_user:
#globus_pass:
#register_gridftp: true|false
#register_myproxy: true|false



### iptables and firewalld
##
### iptables and firewalld are tools that controls the Linux kernel's packet firewall.
### Many sites will likely wish to manage this on their own. If you are
### not familiar with this tool and would like this deployment to
### takes steps to configure the iptables for you on CentOS 6 then
### uncomment the below variable and set it to true. Otherwise your
### site will be responsible for ensuring the proper ports are open.
##
### By default, iptables WILL NOT be configured on CentOS 6, set to true to change this behavior
### By default, firewalld WILL NOT be configured on CentOS 7, set to true to change this behavior
##
#configure_centos6_iptables: true|false
#configure_centos7_firewalld: true|false



### Mirror Host
##
### The ESGF mirror to be used. Defaults to
### aims1.llnl.gov
##
### Choices:
## distrib-coffee.ipsl.jussieu.fr/pub
## dist.ceda.ac.uk
## aims1.llnl.gov
## esg-dn2.nsc.liu.se
##
#mirror_host: aims1.llnl.gov