# This file is an example of what variables may be specified
# for deploying a new data node.
# See the sample myhost.my.org.yml file for all the details
# of these variables and other important information.

### Admin password
admin_pass: myAdminPass

### Keys and Certificates

### Keys and Certificates for Globus Services
generate_globus: true

### Keys and Certificates for Web Services, httpd and tomcat
hostkey_src: /path/on/node/to/hostkey
hostcert_src: /path/on/node/to/hostcert
cachain_src: /path/on/node/to/cachain


## If on CentOS 7, which is strongly recommended for new deployments
### iptables and firewalld
configure_centos7_firewalld: true
