
- name: Tomcat Group
  group:
    name: tomcat

- name: Tomcat User
  user:
    name: tomcat
    groups: tomcat

- name: Tomcat Download
  unarchive:
    src: "{{ tomcat.src }}"
    dest: /tmp
    remote_src: yes

- name: Install tomcat
  command: "cp -R /tmp/{{ tomcat.root_dir }} {{ tomcat.path }}"
  args:
    creates: "{{ tomcat.path }}" 

- name: Cleanup default webapps
  file:
    path: "{{ tomcat.webapps }}/{{ item }}"
    state: absent
  with_items:
    - ROOT
    - manager
    - host-manager
    - examples
    - docs

- name: Set Ownership
  file:
    path: "{{ tomcat.path }}"
    owner: tomcat
    group: tomcat
    recurse: yes