
- name: Tomcat Group
  group:
    name: tomcat

- name: Tomcat User
  user:
    name: tomcat
    groups: tomcat

- name: Tomcat Download
  unarchive:
    src: "{{ tomcat.src }}"
    dest: /tmp
    remote_src: yes

- name: Install tomcat
  command: "cp -R /tmp/apache-tomcat-8.5.20 {{ tomcat.path }}"
  args:
    creates: "{{ tomcat.path }}" 

- name: Set Ownership
  file:
    path: "{{ tomcat.path }}"
    owner: tomcat
    group: tomcat
    recurse: yes