
- name: Tomcat Group
  group:
    name: tomcat

- name: Tomcat User
  user:
    name: tomcat
    groups: tomcat

- name: Tomcat Download
  unarchive:
    src: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.20/bin/apache-tomcat-8.5.20.tar.gz
    dest: /tmp/apache-tomcat-8.5.20
