- name: Retrieve info about what datasets to mount
  fetch:
    src: "{{ esg.config.dir }}/esgcet/esg.ini"
    dest: /tmp/
    flat: yes

- name: Read datasets from esg.ini
  set_fact:
    raw_dataset_roots: "{{ lookup('ini', 'thredds_dataset_roots section=DEFAULT file=/tmp/esg.ini') }}"

- name: Remove fetched esg.ini file
  become: false
  local_action:
    module: file
    path: /tmp/esg.ini
    state: absent

- name: Check what is mounted to avoid remounting
  slurp:
    src: /proc/mounts
  register: mounts

- name: Decode mount file
  set_fact:
    mounts: "{{ mounts['content'] | b64decode }}"

- name: Mount the dataset root directories into the chroot GridFTP
  when: " gridftp.chroot + '/' + item.split(\"|\")[0].strip() not in mounts"
  command: "mount --bind {{ item.split('|')[1].strip() }} {{ gridftp.chroot }}/{{ item.split('|')[0].strip() }}"
  args:
    warn: no
  with_items: "{{ raw_dataset_roots.split('\n')[1:] }}"